AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Metrics/MethodLength:
  Max: 30

Layout/LineLength:
  Max: 120
