AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/FrozenStringLiteralComment:
  Exclude:
    - lib/guard/srb/templates/Guardfile

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 120

Metrics/ClassLength:
  Max: 1024

Layout/LineLength:
  Max: 120
